name = "modelobservatory"
main = "src/server/worker.ts"
compatibility_date = "2026-07-14"
keep_vars = true

[vars]
CACHE_VERSION = "v3"

[assets]
directory = "dist/client"
not_found_handling = "single-page-application"

[triggers]
crons = ["*/4 * * * *"]

[dev]
port = 8788

[observability]
enabled = true

[[kv_namespaces]]
binding = "METRICS"
id = "2da8406333284ec79307b7b75034fec7"
